name = "test"

[[entries]]
ip = "127.0.0.1"
hosts = [
    "aegis.heliannuuthus.com",
    "atlas.heliannuuthus.com",
    "hermes.heliannuuthus.com",
    "zwei.heliannuuthus.com",
    "iris.heliannuuthus.com",
    "chaos.heliannuuthus.com"
]

[[entries]]
ip = "192.168.1.100"
hosts = ["newhost.example.com"]

[[entries]]
ip = "127.0.0.1"
hosts = ["auth.heliannuuthus.com"]
